### ISSUE TITLE
Link Customer UI to Bot

### ISSUE THREAD

**Issue by nickhinchliffe** [nickhinchliffe/ITChatBot#11]
Have the bot receive questions through the Customer UI

**Comment by nickhinchliffe** [comment]
https://cloud.ibm.com/docs/assistant?topic=assistant-api-client

**Comment by nickhinchliffe** [comment]
https://javascript.plainenglish.io/integrate-watson-into-your-react-rails-project-and-look-like-a-real-smart-like-person-yeah-31e350babcaf

**Comment by nickhinchliffe** [comment]
https://github.com/watson-developer-cloud/react-components

**Comment by kaczynskis** [comment]
Assistant Name: IT Chat Bot
Assistant ID: 398fd1c8-a06f-4fdc-b9f1-c553d1878907
Assistant URL: https://api.us-south.assistant.watson.cloud.ibm.com/instances/384648db-6aed-4ceb-871b-321b292ff899/v2/assistants/398fd1c8-a06f-4fdc-b9f1-c553d1878907/sessions
API Key: tuG9mC6jBr9nSf5DVhHqoB22kDtnUOmTkuRbpaDBuCng

**Comment by kaczynskis** [comment]
Service URL: https://api.us-south.assistant.watson.cloud.ibm.com/instances/384648db-6aed-4ceb-871b-321b292ff899
