### ISSUE TITLE
Implement Customer UI

### ISSUE THREAD

**Issue by nickhinchliffe** [nickhinchliffe/ITChatBot#8]
Create working UI Chat interface with React

**Comment by hinchliffen** [comment]
https://www.npmjs.com/package/react-chat-ui library for chat ui

**Comment by nickhinchliffe** [comment]
https://www.freecodecamp.org/news/how-to-clear-input-values-of-dynamic-form-in-react/

**Comment by nickhinchliffe** [comment]
https://www.freecodecamp.org/news/how-to-build-a-react-js-chat-app-in-10-minutes-c9233794642b/
